# Generated by Django 4.0.2 on 2022-05-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
